# Generated by Django 3.0.14 on 2022-01-12 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220112_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following_set',
        ),
        migrations.AlterField(
            model_name='user',
            name='follower_set',
            field=models.ManyToManyField(blank=True, related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
