# Generated by Django 3.0.14 on 2022-01-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramsns', '0003_auto_20220114_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
